services:
    postgres:
        image: postgres:14-alpine
        container_name: pixelverse-postgres
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: auth_db
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        container_name: pixelverse-zookeeper
        restart: always
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:7.5.0
        container_name: pixelverse-kafka
        restart: always
        depends_on:
            - zookeeper
        ports:
            # Exposes Kafka for external connections (our Node.js services)
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            # This listener is for our services to connect to from our host machine
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    hazelcast:
        image: hazelcast/hazelcast:5.3.6
        container_name: pixelverse-hazelcast
        restart: always
        ports:
            # Exposes the default Hazelcast client port
            - "5701:5701"
        environment:
            # Sets up a simple cluster name and password for development
            HZ_CLUSTERNAME: dev-cluster
            HZ_CLUSTERPASSWORD: dev-password

volumes:
    postgres-data:
