POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword123"
}

### LOGIN ###

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword123"
}

### Place pixel ###
POST http://localhost:3002/api/canvas/place-pixel HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyN2FkOTM3NS1kZjcxLTRhNGYtYTVmZC0wM2I3OWU1ZjM2ZGMiLCJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpYXQiOjE3NTMxMTYwMzQsImV4cCI6MTc1MzExOTYzNH0.u1uhNc3H8fFsyLBVaGVhGWAo4yFZbXNXPuDn_IVpHnc
Content-Type: application/json

{
  "x": 111,
  "y": 20,
  "color": "#FF5733"
}
